// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartAgricultuer.Models;

public partial class AnalysisResult
{
    public int Id { get; set; }

    public int UploadId { get; set; }

    public int? DetectedPlantId { get; set; }

    public int? DetectedDiseaseId { get; set; }

    public int? DetectedInsectId { get; set; }

    public bool? IsDiseased { get; set; }

    public decimal? ConfidenceScore { get; set; }

    public DateTime? AnalyzedAt { get; set; }

    public virtual PlantDisease DetectedDisease { get; set; }

    public virtual Insect DetectedInsect { get; set; }

    public virtual Plant DetectedPlant { get; set; }

    public virtual Upload Upload { get; set; }
}