// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartAgricultuer.Models;

public partial class AnalysisType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Upload> Uploads { get; set; } = new List<Upload>();
}