// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using SmartAgricultuer.Models; // اتأكد إن الـ Namespace ده هو اللي عندك فعلاً

namespace SmartAgricultuer.Models;

public partial class AppdbContext : IdentityDbContext<ApplicationUser, IdentityRole<int>, int>
{
    public AppdbContext(DbContextOptions<AppdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AnalysisResult> AnalysisResults { get; set; }
    public virtual DbSet<AnalysisType> AnalysisTypes { get; set; }
    public virtual DbSet<Insect> Insects { get; set; }
    public virtual DbSet<Plant> Plants { get; set; }
    public virtual DbSet<PlantDisease> PlantDiseases { get; set; }
    public virtual DbSet<TreatmentStep> TreatmentSteps { get; set; }
    public virtual DbSet<Upload> Uploads { get; set; }
    public IEnumerable<object> DetectionHistories { get; internal set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // --- السطر الأهم لحل مشاكل الـ Identity ---
        base.OnModelCreating(modelBuilder);
        // ---------------------------------------

        modelBuilder.Entity<AnalysisResult>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Analysis__3213E83FABEA73C9");
            entity.ToTable("Analysis_Results");
            entity.HasIndex(e => e.UploadId, "IX_Result_Upload");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnalyzedAt).HasDefaultValueSql("(sysdatetime())").HasColumnName("analyzed_at");
            entity.Property(e => e.ConfidenceScore).HasColumnType("decimal(4, 3)").HasColumnName("confidence_score");
            entity.Property(e => e.DetectedDiseaseId).HasColumnName("detected_disease_id");
            entity.Property(e => e.DetectedInsectId).HasColumnName("detected_insect_id");
            entity.Property(e => e.DetectedPlantId).HasColumnName("detected_plant_id");
            entity.Property(e => e.IsDiseased).HasDefaultValue(false).HasColumnName("is_diseased");
            entity.Property(e => e.UploadId).HasColumnName("upload_id");

            entity.HasOne(d => d.DetectedDisease).WithMany(p => p.AnalysisResults)
                .HasForeignKey(d => d.DetectedDiseaseId)
                .HasConstraintName("FK_Result_Disease");

            entity.HasOne(d => d.DetectedInsect).WithMany(p => p.AnalysisResults)
                .HasForeignKey(d => d.DetectedInsectId)
                .HasConstraintName("FK_Result_Insect");

            entity.HasOne(d => d.DetectedPlant).WithMany(p => p.AnalysisResults)
                .HasForeignKey(d => d.DetectedPlantId)
                .HasConstraintName("FK_Result_Plant");

            entity.HasOne(d => d.Upload).WithMany(p => p.AnalysisResults)
                .HasForeignKey(d => d.UploadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Result_Upload");
        });

        modelBuilder.Entity<AnalysisType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Analysis__3213E83F4870F86C");
            entity.ToTable("Analysis_Types");
            entity.HasIndex(e => e.Name, "UQ__Analysis__72E12F1B8B75857C").IsUnique();
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name).IsRequired().HasMaxLength(50).HasColumnName("name");
        });

        modelBuilder.Entity<Insect>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Insects__3213E83F09E8468B");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())").HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsDeleted).HasDefaultValue(false).HasColumnName("is_deleted");
            entity.Property(e => e.IsHarmfulDefault).HasDefaultValue(true).HasColumnName("is_harmful_default");
            entity.Property(e => e.Name).IsRequired().HasMaxLength(150).HasColumnName("name");
            entity.Property(e => e.Prevention).HasColumnName("prevention");
            entity.Property(e => e.ScientificName).HasMaxLength(150).HasColumnName("scientific_name");

            entity.HasMany(d => d.Plants).WithMany(p => p.Insects)
                .UsingEntity<Dictionary<string, object>>(
                    "InsectPlant",
                    r => r.HasOne<Plant>().WithMany().HasForeignKey("PlantId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_InsectPlant_Plant"),
                    l => l.HasOne<Insect>().WithMany().HasForeignKey("InsectId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_InsectPlant_Insect"),
                    j =>
                    {
                        j.HasKey("InsectId", "PlantId").HasName("PK__Insect_P__72DCE0CC14EB6994");
                        j.ToTable("Insect_Plants");
                        j.IndexerProperty<int>("InsectId").HasColumnName("insect_id");
                        j.IndexerProperty<int>("PlantId").HasColumnName("plant_id");
                    });
        });

        modelBuilder.Entity<Plant>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Plants__3213E83F5AC6B066");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())").HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.GeneralCare).HasColumnName("general_care");
            entity.Property(e => e.IsDeleted).HasDefaultValue(false).HasColumnName("is_deleted");
            entity.Property(e => e.Name).IsRequired().HasMaxLength(100).HasColumnName("name");
            entity.Property(e => e.ScientificName).HasMaxLength(150).HasColumnName("scientific_name");
        });

        modelBuilder.Entity<PlantDisease>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Plant_Di__3213E83F0DC6A33B");
            entity.ToTable("Plant_Diseases");
            entity.HasIndex(e => e.PlantId, "IX_Disease_Plant");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Causes).HasColumnName("causes");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsDeleted).HasDefaultValue(false).HasColumnName("is_deleted");
            entity.Property(e => e.Name).IsRequired().HasMaxLength(150).HasColumnName("name");
            entity.Property(e => e.PlantId).HasColumnName("plant_id");
            entity.Property(e => e.Prevention).HasColumnName("prevention");
            entity.Property(e => e.Symptoms).HasColumnName("symptoms");

            entity.HasOne(d => d.Plant).WithMany(p => p.PlantDiseases).HasForeignKey(d => d.PlantId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Disease_Plant");
        });

        modelBuilder.Entity<TreatmentStep>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Treatmen__3213E83F4193D6DC");
            entity.ToTable("Treatment_Steps");
            entity.HasIndex(e => e.DiseaseId, "IX_Treatment_Disease");
            entity.HasIndex(e => e.InsectId, "IX_Treatment_Insect");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.DiseaseId).HasColumnName("disease_id");
            entity.Property(e => e.InsectId).HasColumnName("insect_id");
            entity.Property(e => e.StepDescription).IsRequired().HasColumnName("step_description");
            entity.Property(e => e.StepNumber).HasColumnName("step_number");
            entity.Property(e => e.StepTitle).IsRequired().HasMaxLength(200).HasColumnName("step_title");

            entity.HasOne(d => d.Disease).WithMany(p => p.TreatmentSteps).HasForeignKey(d => d.DiseaseId).HasConstraintName("FK_Treatment_Disease");
            entity.HasOne(d => d.Insect).WithMany(p => p.TreatmentSteps).HasForeignKey(d => d.InsectId).HasConstraintName("FK_Treatment_Insect");
        });

        modelBuilder.Entity<Upload>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Uploads__3213E83FAC69991D");
            entity.HasIndex(e => e.UserId, "IX_Upload_User");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnalysisTypeId).HasColumnName("analysis_type_id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())").HasColumnName("created_at");
            entity.Property(e => e.ImageUrl).IsRequired().HasMaxLength(500).HasColumnName("image_url");
            entity.Property(e => e.IsDeleted).HasDefaultValue(false).HasColumnName("is_deleted");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.AnalysisType).WithMany(p => p.Uploads).HasForeignKey(d => d.AnalysisTypeId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Upload_Type");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}