// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartAgricultuer.Models;

public partial class InsectPlant
{
    public int InsectId { get; set; }

    public int PlantId { get; set; }

    public string DamageType { get; set; }

    public virtual Insect Insect { get; set; }

    public virtual Plant Plant { get; set; }
}