// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartAgricultuer.Models;

public partial class Insect
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ScientificName { get; set; }

    public string Description { get; set; }

    public bool? IsHarmfulDefault { get; set; }

    public string Prevention { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Status { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<AnalysisResult> AnalysisResults { get; set; } = new List<AnalysisResult>();

    public virtual ICollection<InsectPlant> InsectPlants { get; set; } = new List<InsectPlant>();

    public virtual ICollection<TreatmentStep> TreatmentSteps { get; set; } = new List<TreatmentStep>();
}