// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartAgricultuer.Models;

public partial class Plant
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ScientificName { get; set; }

    public string Description { get; set; }

    public string GeneralCare { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string CommonDiseases { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<AnalysisResult> AnalysisResults { get; set; } = new List<AnalysisResult>();

    public virtual ICollection<InsectPlant> InsectPlants { get; set; } = new List<InsectPlant>();

    public virtual ICollection<PlantDisease> PlantDiseases { get; set; } = new List<PlantDisease>();
}