// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartAgricultuer.Models;

public partial class PlantDisease
{
    public int Id { get; set; }

    public int PlantId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Symptoms { get; set; }

    public string Causes { get; set; }

    public string Prevention { get; set; }

    public bool? IsDeleted { get; set; }

    public string PlantType { get; set; }

    public string DetectionStatus { get; set; }

    public string VisualEvidenceUrl { get; set; }

    public virtual ICollection<AnalysisResult> AnalysisResults { get; set; } = new List<AnalysisResult>();

    public virtual Plant Plant { get; set; }

    public virtual ICollection<TreatmentStep> TreatmentSteps { get; set; } = new List<TreatmentStep>();
}