// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartAgricultuer.Models;

public partial class TreatmentStep
{
    public int Id { get; set; }

    public int? DiseaseId { get; set; }

    public int? InsectId { get; set; }

    public int StepNumber { get; set; }

    public string StepTitle { get; set; }

    public string StepDescription { get; set; }

    public virtual PlantDisease Disease { get; set; }

    public virtual Insect Insect { get; set; }
}