// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartAgricultuer.Models;

public partial class Upload
{
    public int Id { get; set; }

    // لازم السطر ده يكون موجود عشان ده الـ Foreign Key اللي في الداتابيز
    public int UserId { get; set; }

    public int AnalysisTypeId { get; set; }

    public string ImageUrl { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedAt { get; set; }

    // دي الـ Navigation Property اللي بتخليك توصل لبيانات اليوزر بسهولة
    public virtual ApplicationUser User { get; set; }

    public virtual ICollection<AnalysisResult> AnalysisResults { get; set; } = new List<AnalysisResult>();

    public virtual AnalysisType AnalysisType { get; set; }
}