// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAgricultuer.Models;

#nullable disable

namespace SmartAgricultuer.Migrations
{
    [DbContext(typeof(AppdbContext))]
    [Migration("20260302222453_InitialIdentity")]
    partial class InitialIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsectPlant", b =>
                {
                    b.Property<int>("InsectId")
                        .HasColumnType("int")
                        .HasColumnName("insect_id");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.HasKey("InsectId", "PlantId")
                        .HasName("PK__Insect_P__72DCE0CC14EB6994");

                    b.HasIndex("PlantId");

                    b.ToTable("Insect_Plants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartAgricultuer.Models.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnalyzedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("analyzed_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(4, 3)")
                        .HasColumnName("confidence_score");

                    b.Property<int?>("DetectedDiseaseId")
                        .HasColumnType("int")
                        .HasColumnName("detected_disease_id");

                    b.Property<int?>("DetectedInsectId")
                        .HasColumnType("int")
                        .HasColumnName("detected_insect_id");

                    b.Property<int?>("DetectedPlantId")
                        .HasColumnType("int")
                        .HasColumnName("detected_plant_id");

                    b.Property<bool?>("IsDiseased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_diseased");

                    b.Property<int>("UploadId")
                        .HasColumnType("int")
                        .HasColumnName("upload_id");

                    b.HasKey("Id")
                        .HasName("PK__Analysis__3213E83FABEA73C9");

                    b.HasIndex("DetectedDiseaseId");

                    b.HasIndex("DetectedInsectId");

                    b.HasIndex("DetectedPlantId");

                    b.HasIndex(new[] { "UploadId" }, "IX_Result_Upload");

                    b.ToTable("Analysis_Results", (string)null);
                });

            modelBuilder.Entity("SmartAgricultuer.Models.AnalysisType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Analysis__3213E83F4870F86C");

                    b.HasIndex(new[] { "Name" }, "UQ__Analysis__72E12F1B8B75857C")
                        .IsUnique();

                    b.ToTable("Analysis_Types", (string)null);
                });

            modelBuilder.Entity("SmartAgricultuer.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SmartAgricultuer.Models.Insect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsHarmfulDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_harmful_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Prevention")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prevention");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("scientific_name");

                    b.HasKey("Id")
                        .HasName("PK__Insects__3213E83F09E8468B");

                    b.ToTable("Insects");
                });

            modelBuilder.Entity("SmartAgricultuer.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("GeneralCare")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("general_care");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("scientific_name");

                    b.HasKey("Id")
                        .HasName("PK__Plants__3213E83F5AC6B066");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("SmartAgricultuer.Models.PlantDisease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Causes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("causes");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.Property<string>("Prevention")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prevention");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symptoms");

                    b.HasKey("Id")
                        .HasName("PK__Plant_Di__3213E83F0DC6A33B");

                    b.HasIndex(new[] { "PlantId" }, "IX_Disease_Plant");

                    b.ToTable("Plant_Diseases", (string)null);
                });

            modelBuilder.Entity("SmartAgricultuer.Models.TreatmentStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiseaseId")
                        .HasColumnType("int")
                        .HasColumnName("disease_id");

                    b.Property<int?>("InsectId")
                        .HasColumnType("int")
                        .HasColumnName("insect_id");

                    b.Property<string>("StepDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("step_description");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int")
                        .HasColumnName("step_number");

                    b.Property<string>("StepTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("step_title");

                    b.HasKey("Id")
                        .HasName("PK__Treatmen__3213E83F4193D6DC");

                    b.HasIndex(new[] { "DiseaseId" }, "IX_Treatment_Disease");

                    b.HasIndex(new[] { "InsectId" }, "IX_Treatment_Insect");

                    b.ToTable("Treatment_Steps", (string)null);
                });

            modelBuilder.Entity("SmartAgricultuer.Models.Upload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisTypeId")
                        .HasColumnType("int")
                        .HasColumnName("analysis_type_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Uploads__3213E83FAC69991D");

                    b.HasIndex("AnalysisTypeId");

                    b.HasIndex(new[] { "UserId" }, "IX_Upload_User");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("InsectPlant", b =>
                {
                    b.HasOne("SmartAgricultuer.Models.Insect", null)
                        .WithMany()
                        .HasForeignKey("InsectId")
                        .IsRequired()
                        .HasConstraintName("FK_InsectPlant_Insect");

                    b.HasOne("SmartAgricultuer.Models.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .IsRequired()
                        .HasConstraintName("FK_InsectPlant_Plant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SmartAgricultuer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SmartAgricultuer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartAgricultuer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SmartAgricultuer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartAgricultuer.Models.AnalysisResult", b =>
                {
                    b.HasOne("SmartAgricultuer.Models.PlantDisease", "DetectedDisease")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("DetectedDiseaseId")
                        .HasConstraintName("FK_Result_Disease");

                    b.HasOne("SmartAgricultuer.Models.Insect", "DetectedInsect")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("DetectedInsectId")
                        .HasConstraintName("FK_Result_Insect");

                    b.HasOne("SmartAgricultuer.Models.Plant", "DetectedPlant")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("DetectedPlantId")
                        .HasConstraintName("FK_Result_Plant");

                    b.HasOne("SmartAgricultuer.Models.Upload", "Upload")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("UploadId")
                        .IsRequired()
                        .HasConstraintName("FK_Result_Upload");

                    b.Navigation("DetectedDisease");

                    b.Navigation("DetectedInsect");

                    b.Navigation("DetectedPlant");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("SmartAgricultuer.Models.PlantDisease", b =>
                {
                    b.HasOne("SmartAgricultuer.Models.Plant", "Plant")
                        .WithMany("PlantDiseases")
                        .HasForeignKey("PlantId")
                        .IsRequired()
                        .HasConstraintName("FK_Disease_Plant");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("SmartAgricultuer.Models.TreatmentStep", b =>
                {
                    b.HasOne("SmartAgricultuer.Models.PlantDisease", "Disease")
                        .WithMany("TreatmentSteps")
                        .HasForeignKey("DiseaseId")
                        .HasConstraintName("FK_Treatment_Disease");

                    b.HasOne("SmartAgricultuer.Models.Insect", "Insect")
                        .WithMany("TreatmentSteps")
                        .HasForeignKey("InsectId")
                        .HasConstraintName("FK_Treatment_Insect");

                    b.Navigation("Disease");

                    b.Navigation("Insect");
                });

            modelBuilder.Entity("SmartAgricultuer.Models.Upload", b =>
                {
                    b.HasOne("SmartAgricultuer.Models.AnalysisType", "AnalysisType")
                        .WithMany("Uploads")
                        .HasForeignKey("AnalysisTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Upload_Type");

                    b.HasOne("SmartAgricultuer.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartAgricultuer.Models.AnalysisType", b =>
                {
                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("SmartAgricultuer.Models.Insect", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("TreatmentSteps");
                });

            modelBuilder.Entity("SmartAgricultuer.Models.Plant", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("PlantDiseases");
                });

            modelBuilder.Entity("SmartAgricultuer.Models.PlantDisease", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("TreatmentSteps");
                });

            modelBuilder.Entity("SmartAgricultuer.Models.Upload", b =>
                {
                    b.Navigation("AnalysisResults");
                });
#pragma warning restore 612, 618
        }
    }
}
